name: Testes CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install

      # 👇 FORÇA PERMISSÃO
      - run: chmod +x node_modules/.bin/vitest

      # 👇 EXECUTA DIRETO
      - run: ./node_modules/.bin/vitest run